about_us/urls.py
from django.urls import path
from . import views

app_name = "about_us"

urlpatterns = [
    path('testimony-api/', views.testimony_api, name='testimony-api'),
    path('', views.about, name='about'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
	path('loged/', views.loged, name = 'loged'),
	path('', views.login, name = 'login'),
	path('logout/', views.logout, name = 'logout'),
]

praktikum/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('about_us.urls')),
	path('login/', include('login.urls')),
	path('auth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

about_us/models.py
from django.db import models

class Testimony(models.Model):
    content = models.TextField()
    username = models.CharField(max_length=255)

login/models.py
from django.db import models

# Create your models here.

about_us/views.py
from django.shortcuts import render

from django.contrib.auth import logout
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
import json
from about_us.models import Testimony


def about(request):
    return render(request, 'about.html')
	
@csrf_exempt
def testimony_api(request):
    print("masuk")
    if request.method == 'POST':
        body = json.loads(request.body)
        print(body)
        testimony = Testimony(content=body['testimony'], username=body['username'])
        testimony.save()
        return HttpResponse(200)
    print("masuk get")
    testimony_list = []
    for testimony in Testimony.objects.all():
        testimony_list.append((testimony.content, testimony.username))
        print(testimony.content)
    return JsonResponse({"testimonys": testimony_list})

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as out

# Create your views here.
def login(request):
	return render(request, "login.html", {})

def loged(request):
	if (request.user.is_authenticated):
		request.session['user_email'] = request.user.email
		nama = request.user.first_name + " " + request.user.last_name
		nama = nama.upper()
		return render(request, "loged.html", {'nama' : nama})
	else:
		return redirect('login:login') 

def logout(request):
	request.session.flush()
	out(request)
	return redirect('login:login')

about_us/templates/about.html
{% load static from staticfiles %}
<!DOCTYPE html>

<head>
    <title>About Us</title>
    <link rel="stylesheet" href="{% static 'css/about.css' %}"/>
    
</head>

<script>

    {#var csrftoken = $("[name=csrfmiddlewaretoken]").val();#}
    {#var csrftoken = getCookie('csrftoken');#}

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function updateTestimony() {
        $.get("{% url 'about_us:testimony-api' %}", data => {
            console.log(data)
            var testimonys = data.testimonys;
            var testimonys_div = $('#testimony-container');
            testimonys_div.html("");
            console.log("masuk")
            testimonys.forEach(testimony => {
                console.log("masuk hehe")
                var content = testimony[0];
                var name = testimony[1];
                testimonys_div.append(`<div class="testimony-wrapper"> <blockquote><i class="fas fa-quote-left"></i>` + content + `</blockquote><h4>&ndash; ` + name + `</h4></div>`);
            })

        })

    }

    function onClick() {
        console.log("aabccd");
        var testimony = $('#testimony-text-area').val()
        var username = "{{ request.user }}"
        $.ajax({
                type: "POST",
                url: "{% url 'about_us:testimony-api' %}",
                data: JSON.stringify(
                    {
                        username: username,
                        testimony: testimony,
                    }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                headers: {
                    "X-CSRFToken": csrftoken
                },
                success: result => {
                    updateTestimony();
                }
            }
        );
    }
    $(updateTestimony());

</script>
<body>
{% include 'navbar.html' %}
<section id="about">
    <h1>ABOUT US</h1>
    <div class="green-sq"></div>
    <div class="about-desc">
        <img src="{% static 'img/Logo.jpg' %}">
        <span>
        President Donald Trump signaled he’s open to another summit with North Korea in a pair of 
        tweets Saturday. The president’s message followed a speech by Kim Jong Un last week in which 
        the North Korean leader presented the US with a deadline for moving negotiations between 
        the two countries forward.
      </span>
    </div>
</section>

<section id="testimonial">
    <h1>TESTIMONIALS</h1>
    <div class="green-sq"></div>
    <div id="testimony-container">
    </div>

    {% csrf_token %}

    {% if user.is_authenticated %}
        <h2>Tuliskan Testimonimu</h2>
        <div class="form-wrapper">
            <textarea id="testimony-text-area"></textarea>
            <button onclick="onClick()">Testify!</button>
        </div>
    {% endif %}
</section>

</body>

login/templates/loged.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
		<!-- BOOSTRAP -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
		<link rel = "stylesheet" href = "{% static 'css/login.css' %}">
		<title>Reuse Me</title>
</head>

<body class = "container">
	{% include "navbar.html" %}
	<div style="text-align: center;">
		<br><br><br>
		<br><br><br>
		<h3 style = "margin-top: 18.5vh"> 
			Selamat Datang {{nama}} <br>
		</h3>
	</div>
</body>
</html>

login/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
		<!-- BOOSTRAP -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
		<link rel = "stylesheet" href = "{% static 'css/login.css' %}">
		<title>Reuse Me - Login With Google</title>
</head>

<body class = "container">
	{% include "navbar.html" %}
	<div style="text-align: center;">
		<br><br><br><br><br><br>
		<br><br><br><br><br>
		<a class = "btn btn-link" href="{% url 'social:begin' 'google-oauth2' %}">
			<img id = "googleimage" src = "{% static 'img/google.png' %}">
		</a>
	</div>
</body>
</html>

templates/navbar.html
{% block head %}
{% endblock %}
{% load static %}
		
        <!-- For Bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		
        <!-- Own's static files -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
	</head>
	
    <body>
    	<!-- from bootstrap -->
    		<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navBar" style="background-color: #003575;">
			    
			    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
			        <span class="navbar-toggler-icon"></span>
			    </button>
			    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				    <div class="navbar-nav" id="navBarNav">
				    	<a class="nav-item nav-link nav-head" href="{% url 'about_us:about' %}" style="color: #FFFFFF;">About Us</a>
						{% if user.is_authenticated %}
							<a class="nav-item nav-link nav-head" id="navDaftar" href="{% url 'login:logout' %}" style="color: #FFFFFF;">Logout</a>
						{% else %}
							<a class="nav-item nav-link nav-head" id="navDaftar" href="{% url 'login:login' %}" style="color: #FFFFFF;">Login</a>
						{% endif %}
				    </div>
			    </div>

			</nav>
    		
		{% block content %}
		{% endblock %}